pipeline {
    agent any
    tools {
        jdk 'jdk'
        }
    environment {
            AWS_REGION = 'us-east-1'
            ECR_REPO   = 'currencyservice'
            IMAGE_TAG  = "${BUILD_NUMBER}"
                }

stages {
    stage('Clean workspace') {
        steps {
            cleanWs()
        }
    }
    stage('Checkout from Git') {
        steps {
            withCredentials([usernamePassword(
                credentialsId: 'github-creds', usernameVariable: 'GITHUB_USER', passwordVariable: 'GITHUB_TOKEN')])
            {
            git branch: 'main', url: '<https://github.com/VireshDhuri01/11-Microservices-.git>'
            sh "git pull --rebase <https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/VireshDhuri01/11-Microservices-> main"
            }
        }
    }
	stage('Detect Changes') {
                steps {
                    script {
                def changedFiles = sh(
                    script: 'git diff --name-only HEAD~1 HEAD',
                    returnStdout: true
                     ).trim()
                    echo "Changed files:"
                    echo changedFiles
                def serviceFiles = changedFiles
                    .split('\n')
                    .findAll { it.startsWith("${env.ECR_REPO}/") }
                def applicationChanged = serviceFiles.any { file ->
                    !file.startsWith("${env.ECR_REPO}/manifest/")
                    }
                 env.SERVICE_CHANGED = applicationChanged.toString()
                    echo "${ECR_REPO} application changed: ${env.SERVICE_CHANGED}"
                }
            }
        }
    stage('Build Image') {
        when {
            expression {
                env.SERVICE_CHANGED == 'true'
            }
        }
        steps {
            sh '''
                docker build -t $ECR_REPO:$IMAGE_TAG ./$ECR_REPO
            '''
        }
    }
    stage('Create Respective Repo in ECR') {
       when {
        expression {
            env.SERVICE_CHANGED == 'true'
                }
            }
        steps {
            withCredentials([string(credentialsId: 'access-key', variable: 'AWS_ACCESS_KEY'),
                string(credentialsId: 'secret-key', variable: 'AWS_SECRET_KEY')])
            {
                sh """
                aws configure set aws_access_key_id $AWS_ACCESS_KEY
                aws configure set aws_secret_access_key $AWS_SECRET_KEY
                """
                sh """
                aws ecr describe-repositories --repository-names ${ECR_REPO} --region ${AWS_REGION} || \
                aws ecr create-repository --repository-name ${ECR_REPO} --region ${AWS_REGION}
                """
                }
            }
        }
    stage('Image Tag, Push & Cleanup') {
        when {
            expression {
                env.SERVICE_CHANGED == 'true'
            }
        }
        steps {
            sh """
                aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${params.AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
                docker tag ${ECR_REPO}:${IMAGE_TAG} ${params.AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}:${IMAGE_TAG}
                docker push ${params.AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}:${IMAGE_TAG}
                """
            sh '''
                docker rmi -f $(docker images -q) || true
                '''
            }
        }
    stage('Update Kubernetes Manifest') {
        when {
            expression {
                env.SERVICE_CHANGED == 'true'
            }
        }
        steps {
            script {
            def IMAGE = "${params.AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}:${IMAGE_TAG}"
            sh """ sed -i 's|image: .*|image: ${IMAGE}|' ${ECR_REPO}/manifest/deployment.yml"""
                }
            }
        }
    stage('Push Manifest to GitHub') {
        when {
                expression {
                env.SERVICE_CHANGED == 'true'
                }
            }
        steps {
            withCredentials([usernamePassword(
                credentialsId: 'github-creds', usernameVariable: 'GITHUB_USER', passwordVariable: 'GITHUB_TOKEN')])
                {sh """
            git config user.name "Viresh Dhuri"
            git config user.email "vireshdhuri28@gmail.com"
            git add ${ECR_REPO}/manifest/deployment.yml
            git commit -m "Update image to build ${IMAGE_TAG}" || true
            git push <https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/VireshDhuri01/11-Microservices-.git> HEAD:main
            """
                }
            }
        }
}
